### ISSUE TITLE
Doesn't highlight error for missing constant when const_missing is redefined for class

### ISSUE THREAD

**Issue by luke-gru** [ruby/error_highlight#34]
I'm working on new feature for ruby's test/unit tool and I define `Test::Unit::TestCase.const_missing`. It does some stuff then calls old const_missing like the following (pseudo code):

```ruby
orig = self.method(:const_missing)
def const_missing(name)
  # do some stuff 
   orig.call(name)
end
```

This broke error_highlight tests for missing constant, it wasn't highlighting anymore. I'm not sure if this is fixable or not.

**Comment by mame** [comment]
Can you please write down the executable code and exactly what you expect?

```ruby
class Foo
  $orig = self.method(:const_missing)
  def self.const_missing(name)
    $orig.call(name)
  end
end

Foo::Bar
```

Current:

```
$ ruby test.rb
test.rb:5:in `call': uninitialized constant Foo::Bar (NameError)

    $orig.call(name)
         ^^^^^
        from test.rb:5:in `const_missing'
        from test.rb:9:in `<main>'
```

Maybe what you expect:

```
$ ruby test.rb
test.rb:5:in `call': uninitialized constant Foo::Bar (NameError)

Foo::Bar
   ^^^^^
        from test.rb:5:in `const_missing'
        from test.rb:9:in `<main>'
```

or

```
$ ruby test.rb
test.rb:9:in `<main>': uninitialized constant Foo::Bar (NameError)

Foo::Bar
   ^^^^^
```

The former can be achieved with error_highlight. But `Foo::Bar` is not in `test.rb:5`, so it may be confusing. The latter is quite difficult to achieve with error_highlight.

(I was aware of a similar problem, but had not written about it before, so I have created #35.)

**Comment by luke-gru** [comment]
If you go in Ruby repository and at the top of the `test_error_highlight.rb` you put:

```ruby
klass = Test::Unit::TestCase
def klass.const_missing(name)
  super
end
```
you will see failing tests.

**Comment by mame** [comment]
Sorry, I don't understand the context at all. Why do you need to run the test of error_highlight along with your hack for test-unit gem? Are you proposing to introduce your hack into the test-unit gem?

**Comment by luke-gru** [comment]
Yeah it's a bit confusing, I'll explain. The changes I'm making are not to the test-unit gem, but to ruby's internal testing framework that is used when running ruby's test-suite (`make test-all)`. You can find the file that I'm changing in the ruby repository at `tool/lib/test/unit/testcase.rb`. When I was changing this file to include my hack, all the tests in ruby's test suite were still working except for error_highlight tests. I was thinking that maybe this is a bug in error_highlight itself, maybe it does not work properly when the class (or the parent class) has defined `const_missing`. That is why I reported the issue. To reproduce the issue, you would have to go to the ruby repository and run `make test-all TESTOPTS="test/error_highlight/test_error_highlight.rb"` with the changes in my 2nd comment in this thread.

**Comment by mame** [comment]
Your patch is what I said as 2-1 in #35. Its problem is that the line number shown by the backtrace and the snippet shown by error_highlight are discrepant.

```ruby
class Foo
  def self.const_missing(_)
    super
  end

  Bar
end
```

```
$ ruby -I lib/ test.rb
test.rb:3:in `const_missing': uninitialized constant Foo::Bar (NameError)

  Bar
  ^^^
        from test.rb:6:in `<class:Foo>'
        from test.rb:1:in `<main>'
```

Note that there is no `Bar` in `test.rb:3`.
